# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20171031_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
